#include <stdio.h>

/**
 * Highly divisible triangular number
 * Problem 12
 *
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * Let us list the factors of the first seven triangle numbers:
 *     1: 1
 *     3: 1,3
 *     6: 1,2,3,6
 *    10: 1,2,5,10
 *    15: 1,3,5,15
 *    21: 1,3,7,21
 *    28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred divisors?
 */

float _abs(float delta) {
    if (delta < 0)
        return -1 * delta;
    return delta;
}

int _sqrt(int number) {
    float dx1 = (number * 1.0) / 2;
    float dx2 = (dx1 + (number / dx1)) / 2;
    while (_abs(dx1 - dx2) >= 0.01) {
        dx1 = dx2;
        dx2 = (dx1 + (number / dx1)) / 2;
    }
    return dx2;
}

int factories(int triangle) {
    int divider = 1, count = 0;
    float sqrt_of_triangle = _sqrt(triangle);
    while (sqrt_of_triangle >= divider) {
        if (triangle % divider == 0)
            count += 2;
        divider++;
    }
    return count;
}

int main() {
    int factor = 1, triangle = 0;
    while (factories(triangle) <= 500)
        triangle += factor++;
    printf("%i\n", triangle);
    return 0;
}
